services:
  backend:
    build:
      context: ./src/backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/sailing_team_db
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./src/frontend
    container_name: react-frontend
    ports:
      - "80:80"
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      - POSTGRES_DB=sailing_team_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
